<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6fcc942d37ac39f9bf71f8e4140fd8f1
{
    public static $prefixLengthsPsr4 = array (
        'a' => 
        array (
            'app\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'app\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6fcc942d37ac39f9bf71f8e4140fd8f1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6fcc942d37ac39f9bf71f8e4140fd8f1::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
